version: "3.8"
services:
  log-router:
    depends_on:
    - router-postgres
    build: .
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_DATASOURCE_URL=jdbc:postgresql://router-postgres:5432/router
      - SPRING_R2DBC_URL=r2dbc:postgresql://router-postgres:5432/router
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
  router-postgres:
    image: "postgres:14.4"
    container_name: "router-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=router